### ISSUE TITLE
Allow users to 'favorite' queries

### ISSUE THREAD

**Issue by chrisclark** [groveco/django-sql-explorer#119]
As an organization grows, it becomes increasingly hard to find your go-to queries. Favorites would help this (and probably replace the 'top x most run' section at the top of the index page)

**Comment by gamesbook** [comment]
Sounds good!

**Comment by chrisclark** [comment]
(late reply)

You actually can, sort of, categorize queries today. If you name your queries like:

Marketing - Last Month's Sales
Marketing - Next Month's Sales

etc.

Then explorer will render them in the query list view with a "Marketing" header, and "Last Month's Sales" and "Next Month's Sales" as sub-items under that header. Clicking the header will collapse/expand the sub-items. It's not the best, but you at least use to lend some sort of organization to the query list.

**Comment by chrisclark** [comment]
This is by no means the same thing, but I did just make a change so that explorer shows the most recently run queries *by the current user* at the top of the query list pane, rather than the most recently run queries explorer-wide. Definitely a nice improvement for those users who mostly rely on Explorer for just a handful of reports!

**Comment by gamesbook** [comment]
@chrisclark Have you pushed this change to the repo?  It seems like a good, configurable option to have.

**Comment by lawson89** [comment]
@marksweb the project does now displays the user's most recently run queries (see below)
So I believe in combination with the naming convention mentioned above we can close this one

```
        qll = QueryLog.objects.filter(
            run_by_user=self.request.user, query_id__isnull=False
        ).order_by(
            '-run_at'
        ).select_related('query')
```

**Comment by marksweb** [comment]
@lawson89 I still like the idea of favourites as well as recents.

When I've come close to starting this I've thought of using an M2M with custom through model incase any extra data or logic needs to manage the relationship

**Comment by lawson89** [comment]
Ok sounds good, shouldn't be too bad to implement. After I finish the triage I'll take a crack at it

**Comment by lawson89** [comment]
@marksweb where would you want the favorites to display? As a new menu item - My Favorites ?

**Comment by lawson89** [comment]
@marksweb this one should be ok to close now?

**Comment by marksweb** [comment]
@lawson89 Yeah. I'm waiting for this to merge before I release; https://github.com/pypa/trove-classifiers/pull/128
