### ISSUE TITLE
Excel download?

### ISSUE THREAD

**Issue by gamesbook** [groveco/django-sql-explorer#125]
Is there any possibility for an Excel (alongside the CSV) download?  Any sense of how complex it would be to do this (one option might be to just convert the CSV "on the fly:)?-

**Comment by chrisclark** [comment]
Can you explain the use case? It's simple data and excel seems to handle
csv just fine. What does adding excel support accomplish?



On Jul 22, 2015, at 11:44 PM, Derek Hohls <notifications@github.com> wrote:

Is there any possibility for an Excel (alongside the CSV) download? Any
sense of how complex it would be to do this (one option might be to just
convert the CSV "on the fly:)?-

—
Reply to this email directly or view it on GitHub
<https://github.com/epantry/django-sql-explorer/issues/125>.

**Comment by gamesbook** [comment]
One case is for less sophisticated users that just "expect" data in the right format; there is also the possibility of making, for example, the headers "bold" to add a little more style to the appearance.

Would you be averse to a patch along these lines (assuming you do not want to do it)?

**Comment by chrisclark** [comment]
There are a few requests for different export formats. I'm going to consolidate those under issue #186
