### ISSUE TITLE
Parameterized query error

### ISSUE THREAD

**Issue by engrogerio** [groveco/django-sql-explorer#183]
When I try to run a query with any parameter (example: type=$$enter_type$$),  I get the following error:

AttributeError at /explorer/query/

'str' object has no attribute 'getvalue'

Request Method: 	POST
Request URL: 	http://127.0.0.1:8081/explorer/query/
Django Version: 	1.8.3
Exception Type: 	AttributeError
Exception Value: 	

'str' object has no attribute 'getvalue'

Exception Location: 	/home/rogerio/.virtualenvs/invent18/local/lib/python2.7/site-packages/explorer/actions.py in _package, line 32

**Comment by chrisclark** [comment]
I think you just had an error in your SQL, but because of the return type of the error path in write_csv(), an exception was getting raised instead of properly passing along the error text. That's been fixed.
