### ISSUE TITLE
django-suit package clash

### ISSUE THREAD

**Issue by rcdosado** [groveco/django-sql-explorer#187]
There is an issue with combining django-suit with django-sql-explorer, there is an error generated when i execute django-sql-explorer queries which worked when i removed django-suit in INSTALLED_APPS, i hope you would check this. thank you, nice django app by the way!

**Comment by grantmcconnaughey** [comment]
Please copy and paste the exact error you are getting (terminal output, screenshot, etc.).

**Comment by chrisclark** [comment]
Hey @rcdosado -- just seconding Grant's request for a copy of the error. I'll close this out in another week or so if we don't hear anything.
