### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Wojozoo** [groveco/django-sql-explorer#190]
Hi,

I hope one of you can help me, this is the first time I've tried to install a python script. 
I tried to follow the install instruction in readme, but I didn't get any closer to using the script. 
I also tried to download the source and run `python setup.py install` but I do not know what to do next. 
Can you please point me in the right direction and hopefully help med get this up and running?

Regards

**Comment by mykljohn** [comment]
I'm having trouble with the install as well.  I'm running Django 1.8 and Python 2.7 but here's the error I get:

(django18)19:30 ~ $ pip install django-sql-explorer
Collecting django-sql-explorer
  Downloading django-sql-explorer-0.9.2.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 2.1MB/s 
Collecting Django>=1.6.7 (from django-sql-explorer)
Collecting sqlparse>=0.1.11 (from django-sql-explorer)
Collecting unicodecsv>=0.13.0 (from django-sql-explorer)
Collecting six>=1.10.0 (from django-sql-explorer)
Building wheels for collected packages: django-sql-explorer
  Running setup.py bdist_wheel for django-sql-explorer ... done
  Stored in directory: /home/geeval/.cache/pip/wheels/91/ca/50/6612862ad6ab851f050fb133cf29deb445251cce3f1e2c22cd
Successfully built django-sql-explorer
Installing collected packages: Django, sqlparse, unicodecsv, six, django-sql-explorer
  Found existing installation: Django 1.3.7
    Uninstalling Django-1.3.7:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/django-admin.py'

**Comment by chrisclark** [comment]
Hey there --

Sorry, but general-purpose documentation on how to get a Django/Python app up and running is outside of the scope of this project. I'd recommend reading this: https://docs.djangoproject.com/en/1.9/intro/tutorial01/

Good luck!
