### ISSUE TITLE
[Question / Problem] Parameters

### ISSUE THREAD

**Issue by mykljohn** [groveco/django-sql-explorer#193]
Great Reporting tool!!!  
I'm trying to get the query below to work, but I get this error:
     (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL   
     server version for the right syntax to use near 'AND \r\n GROUP BY u.username, e.EvaluationDate    
     WITH ROLLUP' at line 5")

Select u.username,e.EvaluationDate , `Candidate Name`, count(*) 
     FROM eval_evaluation e 
             LEFT JOIN eval_candidate c ON e.candidate_id=c.id 
             LEFT JOIN auth_user u ON e.user_id=u.id 
     WHERE e.status = 2 AND e.EvaluationDate  BETWEEN $$fdate$$ AND $$tdate$$
     GROUP BY  u.username, e.EvaluationDate  WITH ROLLUP

The query works if I put in date strings instead of the parameters.  If I take out the GROUP BY, I get (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND' at line 5")

Any idea what's going on?  cheers

**Comment by chrisclark** [comment]
I would recommend doing something like:

```
BETWEEN '$$fdate$$' AND '$$tdate$$'
```

Note the string literals around the params. Then you can enter date strings into the generated param UI and should be good to go.
