### ISSUE TITLE
[Problem] Show Schema and Format not working

### ISSUE THREAD

**Issue by mykljohn** [groveco/django-sql-explorer#194]
I'm not sure why, but the Show Schema and Format Tabs do nothing.  Am I missing something?

**Comment by mykljohn** [comment]
Oop found it by looking at the element...
/static/explorer/explorer.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by chrisclark** [comment]
Should I close this issue or do you think there is an actual problem here that we should look to address?

**Comment by mykljohn** [comment]
Oops sorry, I'll close it
