### ISSUE TITLE
Setup instruction (this is not a issue)

### ISSUE THREAD

**Issue by QCR615** [groveco/django-sql-explorer#204]
Hi,
I am new to Django and Java Script and trying to setup Django sql explorer for demonstration purpose. Is there a step by step instruction to setup Django sql explorer? pip installation is not allowed in our environment. I have installed the Django using tar ball file and now trying to put this app on it.
Thanks,

**Comment by chrisclark** [comment]
Hi there -- you should be able to clone to repo and run:

``python setup.py install``

**Comment by mykljohn** [comment]
FYI... You should add Collect static to the instructions.
