### ISSUE TITLE
[Enhancements] PDF Export

### ISSUE THREAD

**Issue by mykljohn** [groveco/django-sql-explorer#207]
Being able to generate PDF reports would be an excellent addition :)

Cheers, Mykl

**Comment by spapas** [comment]
Hello, for pdf export I recommend using xhtml2pdf (forerly pisa): https://github.com/xhtml2pdf/xhtml2pdf 

This is a great tool that internally uses reportlab but, instead of creating the report by hand using the reportlab API you provide an html template that will be used to generate the report. I've written a rather extensive blog post describing some techniques for using xhtml2pdf that you may find useful if you decide to use it: https://spapas.github.io/2015/11/27/pdf-in-django/

**Comment by chrisclark** [comment]
Very interesting! I'll check it out. That might indeed be a more straightforward way to approach this. The reportlab solution is...complicated :)

**Comment by chrisclark** [comment]
I'm thinking of addressing this via #248 - if you want to export to PDF, view the query in fullscreen and use the native browser print dialog to export to PDF. It's just too complex to handle all of the weird edge cases manually creating PDFs in explorer. I'm not against the idea, and if someone submits a kick-ass PR (or finishes mine), I'm fine with that - but it's not an enhancement I'll continue working on beyond the referenced PR. Hope folks can live with this solution!

**Comment by spapas** [comment]
Hello @chrisclark I can give a try implementing this using reportlab and xhtml2pdf. Could you reopen the issue?

Thanks !

**Comment by grantmcconnaughey** [comment]
I like the idea of having an export to PDF button if possible. That way all of the export options are the same. Agreed that we would need a PR that handles all of the edge cases in generation, though.

**Comment by spapas** [comment]
@grantmcconnaughey with the xhtml2pdf way I propose in #249 most edge cases are more or less handled by overriding the default template (i.e you can easily add a font that supports unicode characters).

We could offer even more control, for example allow the user to define a specific pdf-output template for each query however this seems like an overkill to me right now. After all, if there's a very special query that needs a very special output format, not covered by the generic (or overriden) pdf-output template the best way to convert it to pdf is to get the XLSX, format it whichever way you like and save it to PDF!

**Comment by grantmcconnaughey** [comment]
@spapas I'm all for going the xhtml2pdf way. I've used that library before and had pretty good success with it.

It would give us the ability to let users override a base PDF template, too. That way users could do custom styles for the PDF reports, which would be an awesome feature.
