### ISSUE TITLE
UnicodeEncodeError if the param $$name$$ contains a non-English character

### ISSUE THREAD

**Issue by legios89** [groveco/django-sql-explorer#209]
Hi!
First of all, this is an amazing tool!
So what I just found that if the param contains a non-English character then I will receive an UnicodeEncodeError. For example, in my case, the Hungarian alphabet contains characters like this "áóőúű" and if `$$name$$` variable contains any of this then you will receive this error.

**Comment by chrisclark** [comment]
Thanks for the bug report! I *hate* unicode errors :( Happy to accept a PR for it, or can try to take a look next week. It won't make it into the next release unfortunately.
