### ISSUE TITLE
UI Enhancement: Allow Users to Pin Open Schema

### ISSUE THREAD

**Issue by raiderrobert** [groveco/django-sql-explorer#211]
**Situation**: when a user searches a query in the playground or other views, the Schema viewer is automatically hidden, because the page reloads. This can lead to the user re-opening the Schema viewer multiple times as they try out a query.

**Suggested Solution**: Let this be set on a per session basis at least with javascript with a checkbox right above the schema viewer that says something like, "Keep Open".

**Comment by chrisclark** [comment]
I'd actually prefer to skip the checkbox, and just cookie the user when they open the schema. If the cookie is set, then render the schema. If they close the schema, unset the cookie. In other words, no UI changes, but the schema toggle becomes sticky across pages.

**Comment by raiderrobert** [comment]
@chrisclark I like the sound of that better too.
