### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by dsanders11** [groveco/django-sql-explorer#216]
I don't have a lot of detail here, unfortunately, this is more of an exploratory issue.

Have you seen any evidence of memory leaks? I seem to be constantly taking down my server by running queries in SQL Explorer. Sometimes I can recover by restarting the application, but sometimes it becomes so unresponsive I can't SSH into it either and the whole thing is effectively locked and a server restart is the only way to fix it.

When I can recover, restarting frees a lot of memory, which is why I believe this to be a memory leak. CPU never gets very high, the server just locks up due to lack of memory.

This is always directly correlated to me running queries in SQL Explorer, usually queries with a few thousand rows (taking advantage of the awesome pivot table feature!) so it seems pretty clear that something is leaking the memory when doing these queries.

**Comment by dsanders11** [comment]
[Here are some screenshots of top](http://imgur.com/a/6KaR4) on the server after running several large queries (and extending the view to 6,000 or 7,000 after the default 1,000). Available memory drops from 252 MB to 89 MB in the last screenshot over the course of about 10 minutes, just by running some queries in SQL Explorer.

**Comment by chrisclark** [comment]
Interesting. It's totally possible that this is happening, though I haven't
noticed it. Can you duplicate this running locally as well? I can take a
crack at tracking this down next week, but am under the gun for another
project for the next few days.

Thanks for the report.

On Jul 20, 2016, at 10:06 PM, David Sanders <notifications@github.com>
wrote:

Here are some screenshots of top <http://imgur.com/a/6KaR4> on the server
after running several large queries (and extending the view to 6,000 or
7,000 after the default 1,000). Available memory drops from 252 MB to 89 MB
in the last screenshot over the course of about 10 minutes, just by running
some queries in SQL Explorer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/groveco/django-sql-explorer/issues/216#issuecomment-234157902>,
or mute the thread

**Comment by dsanders11** [comment]
Much appreciated @chrisclark. I'll try to find some more details for you if I can, but I'm also pretty under the gun. Now that I know what is causing the leak I can avoid it, for a bit there was dreading trying to hunt down a mystery memory leak.

Worth noting I'm running a slightly modified 0.9.2, which is really just 0.9.2 + a couple PR requests you accepted and are in 1.0.0 and a few cosmetic CSS changes. I'll try to update to 1.0.0 over the weekend and confirm it still reproduces there just to narrow it down.

Since you know the API, is there an easy way to run saved queries from the Django shell? I could save the query I used to produce the results in the screenshots and then run it from shell several times and see if I get similar results. Could either eliminate or implicate the user interface code, always nice to bisect the area to search.

**Comment by jproffitt** [comment]
@dsanders11 were you able to find any other details? I did some digging, and it does seem like there is a leak somewhere. Did you have `DEBUG` turned on by any chance?

**Comment by dsanders11** [comment]
@jproffitt, I have not found any other details, no. I see the leak in production with `DEBUG` turned off, and haven't had a chance to look further into it.

**Comment by chrisclark** [comment]
I just spent some time with pympler trying to find a leak and was unable to make any progress.

If anyone wants to give this a try for themselves, I was doing:

``` python
>>> from explorer.models import Query
>>> q = Query(sql="select * from explorer_querylog;")
>>> from pympler import tracker
>>> tk = tracker.SummaryTracker()
>>> tk.print_diff()
>>> q.execute_with_logging(None)
>>> tk.print_diff()
```
To try and see what was happening, and no luck. There are no globals, and I can't find any reference cycles, so it's hard to imagine what's causing it, short of Django failing to release objects at the end of a request/response cycle, which seems unlikely. I'm happy to look further into it, but just not sure where to look next.

**Comment by dsanders11** [comment]
I've looked into this some more and was also not able to definitively track down a memory leak. I did isolate the high memory usage to the `preview_pane.html` template, however. I see the high memory usage when using the Playground for big queries, but if I change the templates to not include `preview_pane.html` then I do not, even though the same query is still being executed.

My current working theory is that it's not necessarily a memory leak, but memory fragmentation in Python. This is going to turn into a long comment, so apologies @chrisclark.

The query I've been using to reproduce the high memory usage selects rows from a table in the database with 10+ columns, and there's 10,000+ rows. I limit it to 10,000 rows in the `SELECT`. For easy math lets say 10 columns and 10,000 rows - that means there's 100,000 cells being generated and rendered.

That's a lot of small objects being created in memory during that playground query. Looking into how Django renders for loops and how sql-explorer is rendering the `preview_pane.html` template, you can kind of see why that might be problematic. The template loops through all rows, and then each column in the row. When rendering for loops in Django's templating it looks like Django stores the output of each for loop iteration and finally concatenates them at the end. So that means on row 10,000 column 10, the template rendering has a list of 9,999 strings for the outer loop and and another 9 for the inner loop.

This makes the rendering ripe for memory fragmentation, where all of those small strings have poked so many small shaped holes into the memory heap that it looks sort of like swiss cheese. Ideally if all of the objects were freed (no memory leak) then all that memory would be returned, but Python and glibc have some historical problems around memory fragmentation and memory return. [\[1\]](#historical-memory-fragmentation-1) [\[2\]](#historical-memory-fragmentation-2)

My production setup also uses threads, which probably exacerbates the problem. Since all threads are sharing memory of the single process, if a worker thread decides to put something in memory long-term for caching purposes (mostly happens when the worker handles its first request) it might put something into memory right in the middle of those tens of thousands of objects that were created during the template rendering and once those are all freed but the one object remains, memory usage is now stuck at that 'high water mark'. That process now has a lot more memory in use then it may need or use, but it's stuck there.

There are a couple possible ways to mitigate this. I'm currently running Python 2.7, but Python 3 has made improvements to memory usage which helps address memory fragmentation and lower memory usage in general. [\[3\]](#python-3-glibc) Obviously that's not something you can flip to over night (though `django-sql-explorer` supports Python 3 👍 ). I've started the process of migrating dependencies though, and hope to get to Python 3 by the new year, so I'll report any improvements regarding this issue that I see.

What can be done overnight, however, is switching to the [`jemalloc`](http://jemalloc.net/) memory allocator, which has less memory fragmentation issues. When used with Python 2.7 it shows much better memory reclaim - running a test script I saw it return to base usage where as without `jemalloc` it would stay 25x higher. [\[4\]](#python-jemalloc) Implementing this in production has had mixed results, I can't tell how much of a difference it is actually making in a real world environment compared to a test script. Unfortunately that's part of the nature of memory fragmentation, it depends partially on chance.

I'm going to close this issue for now since I don't think there's anything actionable for this project short of a larger refactor (which I may open an issue for).

References
1. <a name="historical-memory-fragmentation-1" href="http://www.evanjones.ca/memoryallocator/">Improving Python's Memory Allocator</a>
2. <a name="historical-memory-fragmentation-2" href="https://mail.python.org/pipermail/python-dev/2015-October/141920.html">[Python-Dev] under what circumstances can python still exhibit "high water mark" memory usage?</a>
3. <a name="python-3-glibc" href="http://bugs.python.org/issue11849">Issue 11849: glibc allocator doesn't release all free()ed memory</a>
4. <a name="python-jemalloc" href="https://nuald.blogspot.com/2013/06/memory-reclaiming-in-python.html">Memory reclaiming in Python</a>
