### ISSUE TITLE
Split "save" and "run"

### ISSUE THREAD

**Issue by pkaczynski** [groveco/django-sql-explorer#227]
Modyfing queries that return a lot of data is quite difficult. I usually end up on cancelling script in firefox, because it takes too long. 

Can you please make two distinct buttons - save (and validate query) and run which shows (or refreshes) the results table.

Thanks for a great app, btw.

**Comment by chrisclark** [comment]
I totally agree with this. There should be some way of doing just a 'save' (though I do think running the query should also save it -- so we'd have 2 buttons: "Save & Run" and "Save Only"). I will try to get to this next week. Thanks for the suggestion!
