### ISSUE TITLE
Ability to create dashboards

### ISSUE THREAD

**Issue by vikasgulati** [groveco/django-sql-explorer#230]
When there are too many SQL reports to be tracked the explorer becomes un-manageable. 

Having an ability to create beautiful dashboard would be great by combining charts from different queries would be wonderful.

Something like [dashboards in blazer](https://blazerme.herokuapp.com/dashboards/1-dashboard-demo)

**Comment by gamesbook** [comment]
A simpler, but still useful, would be allow reports to be part of a group/sub-group hierarchy; and also allow them to be tagged.  That would make filtering fairly quick.

**Comment by chrisclark** [comment]
Some organization (though definitely not dashboards) is sorta-kinda already possible through a not-very-well documented feature: You can name queries like this:

`topic - title`

and the explorer list view will build pseudo-folders. Here's a screenshot -- you can see that the "Marketing" heading has 9 queries and is collapsed. You can collapse/uncollapse topics by clicking the header.

![screen shot 2016-11-04 at 5 21 40 pm](https://cloud.githubusercontent.com/assets/693700/20026100/3a44ddec-a2b3-11e6-812c-a5e5c87669e8.png)

Dashboards are probably not in the cards for a long time to come, but I would love to make large numbers of queries more manageable.
