### ISSUE TITLE
v0.6 preview not working?

### ISSUE THREAD

**Issue by kostiag** [groveco/django-sql-explorer#233]
Hi,
Apologies if this is simple question I am a newbie to Django and perhaps that is where my lack of understanding coming from. I have everything setup and working, however when I attempt to preview results in the browser link is (https://xxxxxx.com/admin/r/36/2/)  I get redirected to https://example.com/explorer/2/. Subbing to https://xxxxxx.com/explorer/2/ or going directly to https://xxxxxx.com/admin/r/36/2/ or variation is not working. Can anyone advise what needs to be done please?

**Comment by chrisclark** [comment]
Hi -- it sounds like your URL configuration is misset. I'm sorry but debugging that is outside of the scope of issues with this project, so I'm going to close it. If you have reason to believe there is a real problem with the project, feel free to reopen. I suggest checking out the Django docs on URL config and re-reading the installation instructions here. Best of luck!
