### ISSUE TITLE
Python3.5: Email address breaks Email CSV 

### ISSUE THREAD

**Issue by csindle** [groveco/django-sql-explorer#235]
To reproduce:

From the web interface running Python3 (specifically 3.5), enter an email address with the email_csv icon and send.  The logs show that the task fails with the [attached](https://github.com/groveco/django-sql-explorer/files/469591/error.txt) traceback. 

Versions:
- django-sql-explorer:
  1.0
- Python: 3.5.2
- Celery: 3.1.23 (Cipater)
- Django: 1.10.1

```
Task explorer.tasks.execute_query with id aa7b7eeb-8f5a-4636-8ba9-7234d7f59c85 raised exception:
'TypeError("a bytes-like object is required, not \'str\'",)'


Task was called with args: ['13', 'brad@example.com'] kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/opt/xyz/env/web/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/xyz/env/web/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/xyz/env/web/lib/python3.5/site-packages/explorer/tasks.py", line 27, in execute_query
    resp = _upload('%s.csv' % random_part, exporter.get_file_output())
  File "/opt/xyz/env/web/lib/python3.5/site-packages/explorer/tasks.py", line 50, in _upload
    return conn.upload(key, data)  # expects a file-like object

<snip>

  File "/usr/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by chrisclark** [comment]
Hmm, very weird -- this code path is tested with both a success and a failure case. In `test_tasks.test_async_results`, you can see that a file-like object is being provided to `conn.upload`. Can you provide the snipped stacktrace? And do all the tests pass locally?

Last thing I'd suggest is trying to duplicate this on HEAD of master instead of the 1.0 release. Sorry I don't have a simple answer!

**Comment by chrisclark** [comment]
Please feel free to reopen if you still experience this on master, but I've been unable to duplicate so I am going to close for now.

**Comment by chrisclark** [comment]
Please feel free to reopen if you still experience this on master, but I've been unable to duplicate so I am going to close for now.
