### ISSUE TITLE
Always show schema window -- settings 

### ISSUE THREAD

**Issue by ndanielsen** [groveco/django-sql-explorer#237]
First, thanks for this great django app. Super helpful. 

It would be helpful to an option to always show the 'schema' view column. It currently disappears after every query is run. 

Thanks for this project. It's also and seriously super easy to plug into my side project!

**Comment by chrisclark** [comment]
Thanks for the kind words! If you run off of master, you'll see that we've actually done this :)

https://github.com/groveco/django-sql-explorer/issues/211

I'm working on a new release that should be ready in a week or so.
