### ISSUE TITLE
Schema preview should respect EXPLORER_CONNECTION_NAME 

### ISSUE THREAD

**Issue by spapas** [groveco/django-sql-explorer#245]
Hello,

the schema preview is always using the "default" SQL connection while it should use the setting defined in EXPLORER_CONNECTION_NAME instead. 

I know that the reason for this is to use a read only connection for EXPLORER_CONNECTION_NAME which is the same as the default connection, however after some tests it seems that the django-sql-explorer works great with a totally different connection than the default as the EXPLORER_CONNECTION_NAME. So, what I did is that I used the default connection for the the users and django stuff of django-sql-explorer and added a second connection to a totally different database which I run queries on.

This actually is related to issue #115, however fixing this issue (respect EXPLORER_CONNECTION_NAME  for schema preview) should be much easier.

**Comment by chrisclark** [comment]
Yep - great issue. Will address. Thanks!

**Comment by chrisclark** [comment]
Fixed with the merge of #257
