### ISSUE TITLE
How to modify settings to allow all user to see queries?

### ISSUE THREAD

**Issue by JeongyongShin** [groveco/django-sql-explorer#253]
you know, currently setting is available for admin only.
I want all users can user queries made by admin with read only permission.
How can I do that?

**Comment by chrisclark** [comment]
Sure - you can do that. You'll want to add something like this to your settings file:

`EXPLORER_PERMISSION_VIEW = lambda u: u.is_authenticated()`

More information in the settings section of the readme.
