### ISSUE TITLE
SCHEMA in blacklist triggering too easily

### ISSUE THREAD

**Issue by jleclanche** [groveco/django-sql-explorer#255]
I'm not sure this is intended but a query such as `SELECT ... FROM pg_tables t WHERE t.schemaname = 'public';` is hitting the blacklist because of `t.schemaname` (triggering on `SCHEMA` which is in the default one).

In fact I'm not really sure why `SCHEMA` is in the blacklist by default?

**Comment by chrisclark** [comment]
Fair point. It's an overridable setting, but I also don't see the reason to have SCHEMA in there. Removed.
