### ISSUE TITLE
Conflict with Django Debug Toolbar?

### ISSUE THREAD

**Issue by eduvik** [groveco/django-sql-explorer#256]
If I have Django Debug Toolbar installed (currently on 1.5), I get the following error when browsing to /explorer/:
```
TypeError at /explorer/ 
process() takes exactly 2 arguments (3 given)

```
If I remove DjDT things work fine. I haven't looked into it in any more depth.

**Comment by chrisclark** [comment]
I can't seem to duplicate the issue. I've run it with both DjDT 1.4 and 1.5 and seems to work fine. But it's possible I've installed Explorer differently, or have my virtualenv set up differently, do don't have a namespace conflict that you have. It seems sort of unlikely to me that Explorer could cause this error (it seems more like a DjDT issue), but keep me posted if you can find any other information. I'm going to close this in the mean time.

![screen shot 2016-11-23 at 10 27 43 am](https://cloud.githubusercontent.com/assets/693700/20574039/86212d98-b167-11e6-8aa9-1adc7944c051.png)
