### ISSUE TITLE
Tag For 1.0 Release

### ISSUE THREAD

**Issue by dsanders11** [groveco/django-sql-explorer#263]
Could you create a tag for the 1.0 release? It's useful to have tags of releases, especially when reconciling forks with changes that have happened since they forked. I think the commit to tag would be 9d49249f44bd3d6162f20eeb223710a84ccacab9 but might need to be double checked.

**Comment by chrisclark** [comment]
Wound up with a tag called v1.0 instead of 1.0 which I'm not trying to delete. Whoops.

I always push tags prior to release. Weird that I missed it at 1.0.
