### ISSUE TITLE
1.0 Bugs

### ISSUE THREAD

**Issue by dsanders11** [groveco/django-sql-explorer#265]
Finally got around to upgrading to 1.0 and ran into various things I fixed that are worth mentioning, but too much of a hassle to button up into separate pull requests.

* xframe same origin regression for schema view (I see master has moved to CBV's, so would need to see how to apply it to that situation: dsanders11/django-sql-explorer@d6b08f963183a11860883c4fa26198a703b327f9
* HTML validation issues. Clean HTML helps catch errors that might cause problems. dsanders11/django-sql-explorer@eda825100684356af1463b511c7079a6b1d4c694 and dsanders11/django-sql-explorer@cc7e9e2852d12c9b8b29b32ea0c264197749de60
* Invalid HTML and a security bug that lets you change the user on existing queries: dsanders11/django-sql-explorer@6d5bc3b9bdc2ee96e52af41a58af3c87cb453f9a
* Mismatched HTML elements (missing closing div tag): dsanders11/django-sql-explorer@367776aa3192c8cbafaf30889d3213743bd1745e

**Comment by chrisclark** [comment]
Think I got all of them! Thanks as always.

**Comment by dsanders11** [comment]
Only thing that looks like it may have gotten missed is with the `iframe` in templates to remove `frameborder="0"` (not valid HTML anymore, hence CSS to replace it) and dropping the "px" in the width since that's also not valid HTML.
