### ISSUE TITLE
pip install replaces Django 1.10.4 with 1.9.12

### ISSUE THREAD

**Issue by rboe** [groveco/django-sql-explorer#268]
Log:
```
C:\Windows\system32>pip install django-sql-explorer
Collecting django-sql-explorer
  Downloading django-sql-explorer-1.0.tar.gz (129kB)
    100% |################################| 133kB 1.1MB/s
Collecting Django<1.10,>=1.7.0 (from django-sql-explorer)
  Downloading Django-1.9.12-py2.py3-none-any.whl (6.6MB)
    100% |################################| 6.6MB 237kB/s
Collecting sqlparse>=0.1.18 (from django-sql-explorer)
  Downloading sqlparse-0.2.2-py2.py3-none-any.whl
Collecting unicodecsv>=0.14.1 (from django-sql-explorer)
  Downloading unicodecsv-0.14.1.tar.gz
Collecting six>=1.10.0 (from django-sql-explorer)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: Django, sqlparse, unicodecsv, six, django-sql-explorer
  Found existing installation: Django 1.10.4
    Uninstalling Django-1.10.4:
      Successfully uninstalled Django-1.10.4
  Running setup.py install for unicodecsv ... done
  Running setup.py install for django-sql-explorer ... done
Successfully installed Django-1.9.12 django-sql-explorer-1.0 six-1.10.0 sqlparse-0.2.2 unicodecsv-0.14.1
```
I'm a python newbie and not sure whether this is a problem in pip or in the django-sql-explorer package.

**Comment by skorokithakis** [comment]
It's because of django-sql-explorer, it doesn't support 1.10 and it seems that your requirements don't specify a Django version (since you're just installing it from the command line), so pip is trying to be helpful and installing the Django version that is supported. I'm here because of the same problem as well, we need to use DSE with 1.10 and we can't.

**Comment by rboe** [comment]
I was a bit confused because the requirements.txt in github were updated some months ago to:
`Django>=1.7.0`
But the package on PyPi is older and reuqires `Django>=1.7.0,<1.10`
BTW, I reinstalled Django with 1.10.4 after installing django-sql-explorer and as far as I can tell it works.

Other option would probably be to pull the master branch from github and use that directly.
