### ISSUE TITLE
Schema Preview does not show anything when database is MySQL

### ISSUE THREAD

**Issue by anilshanbhag** [groveco/django-sql-explorer#269]
After a bit of digging, the problem is that the app name is hardcoded in the SQL query run
https://github.com/groveco/django-sql-explorer/blob/master/explorer/schema.py#L94

If we make it the app name, it should work.

**Comment by leehinde** [comment]
I just upgraded my local dev version and I think I just got bit by this: I got a javascript runtime error:

Error: The list need to have at list one item on init otherwise you'll have to add a template. (list.min.js)

and no Schema data.

**Comment by artschwagerb** [comment]
#291
