### ISSUE TITLE
db-agnostic question

### ISSUE THREAD

**Issue by startmat** [groveco/django-sql-explorer#270]
Hi Chris,
first of all: "I like the project and the idea :-)". Especially the hopefully db-agnostic future. I have one question is there are reason why you do not use the django introspection to get the database tables for the schema bowser. I think if you use it than you have all django ORM layer supported databases out of the box: 

https://github.com/django/django/blob/master/django/core/management/commands/inspectdb.py

I have done an fast forward implementation in schema.py. Looks like it is working with Oracle (tested with one table) and sqlite:

    def schema_info(connection):
        ret = []
        with connection.cursor() as cursor:
            tables_to_introspect = connection.introspection.table_names(cursor)
            for table_name in tables_to_introspect:
                td = []
                table_description = connection.introspection.get_table_description(cursor, table_name)
                for row in table_description:
                    column_name = row[0]
                    field_type = connection.introspection.get_field_type(row[1], row)
                    td.append((column_name, field_type))
                ret.append((table_name, td))
        return ret

br
Matthias

**Comment by chrisclark** [comment]
This is done and working!

I like it for its robustness, but it also turns out it is quite slow. I did it anyway though; and added the optional capability to build the schemas in the background, asynchronously, via Celery. Just merged it all into master!
