### ISSUE TITLE
tinyS3 in optional-requirements has been abandoned

### ISSUE THREAD

**Issue by lsh-0** [groveco/django-sql-explorer#276]
tinyS3 in the optional requirements, used to upload query results to s3, doesn't appear to work with Python3.6 and has been/may have been abandoned: https://github.com/smore-inc/tinys3/issues/45

**Comment by chrisclark** [comment]
Replaced with Boto in #287

**Comment by lsh-0** [comment]
hey, thanks for updating this. good to know. I might be able to tear out a chunk of custom code now...
