### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by skorokithakis** [groveco/django-sql-explorer#277]
Can we get a new release? For some reason, pip does not want to install DSE from the repo, which means we can't use it at all unless the <=1.9 requirement is gone.

**Comment by skorokithakis** [comment]
Any luck here? Our requirements are unsatisfiable because of DSE.

**Comment by chrisclark** [comment]
Hey hey! OK -- will do a release by March 17. Apologies for the radio silence -- my day job has been keeping me more than occupied since the beginning of the year :)

**Comment by chrisclark** [comment]
2 days later than promised, but just released 1.1.0 on pypi. Thanks for your patience everyone!
