### ISSUE TITLE
Downgrades you to Django 1.9

### ISSUE THREAD

**Issue by annashres** [groveco/django-sql-explorer#290]
Installing django-sql-explorer uninstalls Django 1.10.6 and reinstalls Django 1.9.12. I am using django-pyodbc-azure (1.10.4.0) to connect to SQL Server. django-pyodbc-azure depends on Django 1.10.4 and up.
After the uninstall/reinstall happens I can then upgrade Django back to 1.10.6 and django-sql-explorer works great. 
Issue is it should not uninstall your existing django and make you upgrade.

**Comment by chrisclark** [comment]
It seems very unlikely to me that that is the case. In both requirements.txt and setup.py, the requirement is just specified as Django>=1.7. It must be another dependency, not SQL Explorer. Is that possible?

**Comment by annashres** [comment]
Yup repo'd and it didn't happen, must be another package. Thanks!
