### ISSUE TITLE
Is it possible or have a plan to support general SQL Explorer?

### ISSUE THREAD

**Issue by northtree** [groveco/django-sql-explorer#294]
It seems only support SQL Explore for Django app/scheme. Is there any plan to support general SQL explore just like phpmyadmin?

**Comment by chrisclark** [comment]
Absolutely! In fact -- there is a very functional branch for doing exactly that. See:

https://github.com/groveco/django-sql-explorer/pull/247

It's pretty much ready for prime time except for this one weird failing test. I will get around to releasing it soon.
