### ISSUE TITLE
No link building on result

### ISSUE THREAD

**Issue by ebertti** [groveco/django-sql-explorer#295]
The results was marked as unsafe, and link was not build correctly

**Version:**
1.1.1

```
EXPLORER_TRANSFORMS = [
    ('offer_id', '<a href="/admin/legacy/offer/{0}/change">{0}</a>'),
]
```

![image](https://user-images.githubusercontent.com/140394/28225779-2c23d958-68aa-11e7-89f3-4a4386f9ed04.png)

**Comment by chrisclark** [comment]
Hmmm...

I can't duplicate (though I'm on the tip of master). I'm seeing:

<img width="519" alt="screen shot 2017-08-06 at 2 58 34 pm" src="https://user-images.githubusercontent.com/693700/29008760-d42aaef0-7ab7-11e7-8977-981094f07a8e.png">

With configuration:

```
EXPLORER_TRANSFORMS = [('shipment', '<a href="https://www.grove.co/admin/orders/shipment/{0}/">{0}</a>')]
```

Can you give it a shot on master?

Not sure what to do from here. I'll leave it open for another couple of days in case you have any additional debugging info you can provide.

**Comment by joeyespo** [comment]
I'm seeing the same thing on `1.1.1`.

At a quick glance, looks like it may have been introduced by [this fix](https://github.com/groveco/django-sql-explorer/pull/286/files#diff-af55d2808c9fcdd580b2214fe70c2530) since transforms are done [sooner](https://github.com/groveco/django-sql-explorer/blob/adb3bf8b12350e875b02db43409ca07c7368f576/explorer/models.py#L189-L194).

SQL Explorer has been such an awesome project btw 😃

**Comment by joeyespo** [comment]
I just tried using `master` (`git clone` + `pip install -e .`). After fixing a few errors, I still saw this behavior.

For reference, I was seeing `ModuleNotFoundError: No module named 'app_settings'`, and here's how I fixed them before I could migrate and run:

#### forms.py
```diff
-   import app_settings
+   from . import app_settings
    
-   from explorer.models import Query, MSG_FAILED_BLACKLIST
-   from explorer.app_settings import EXPLORER_DEFAULT_CONNECTION
+   from .models import Query, MSG_FAILED_BLACKLIST
+   from .app_settings import EXPLORER_DEFAULT_CONNECTION
```

#### utils.py
```diff
    def get_valid_connection(alias=None):
-       from app_settings import EXPLORER_DEFAULT_CONNECTION
-       from connections import connections
+       from .app_settings import EXPLORER_DEFAULT_CONNECTION
+       from .connections import connections
```

**Comment by ebertti** [comment]
Hi!

Exploring the code, I found this configuration that can enable the links using Transforms:

```python
# settings.py
EXPLORER_UNSAFE_RENDERING = True
```

**Comment by chrisclark** [comment]
Yep — that’s the ticket. The documentation should be much cleare on this point. I will address.

Thanks all!
