### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by bradmerlin** [groveco/django-sql-explorer#309]
Hey Groveco,

Do you have plans to add Django 2.0 support? If not, I don't mind submitting a PR. Let me know.

Thanks for open-sourcing SQL Explorer!

**Comment by skorokithakis** [comment]
Please merge this PR and release, Django 2 is out now.

**Comment by daneah** [comment]
Worked independently this morning on the issues that #312 and #313 resolve and concur that the changes seem pretty appropriate! Let us know if we can help in getting a new release out! 😄
