### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by ojotoxy** [groveco/django-sql-explorer#318]
Hey, great work on this tool!

I'm thinking it might be good to release a new version on pip. There's some good stuff in the latest version, esp a fix for showing the schema on mysql.

I added this to my pip requirements list:
```
git+git://github.com/groveco/django-sql-explorer.git@42237747b82aba40340bdbe1534fe2c085f96b01 # latest commit as of jan 12 2018
```

and had to pip uninstall the current version first.

This could be confusing for many users and I'm sure they would appreciate a release on pip.

**Comment by daneah** [comment]
@chrisclark is there anything we can do to help get a new release out the door? Would love to see the Django 2.0 compatibility available in PyPI!

**Comment by chrisclark** [comment]
Hi folks -- I will add Django 2 to the travis file and see where we're at. If it passes, I will release.

**Comment by pahaz** [comment]
any updates?

**Comment by daneah** [comment]
Django 2 has been added to the `.travis.yml` and the build is still passing. Would really love a release at this point!

**Comment by daneah** [comment]
@chrisclark do you have any availability to make a new release? If you're bogged down, are you looking for anyone to take over this project? Thanks!

**Comment by daneah** [comment]
Can any of @gitneha, @katekligman, @lindsayemarc, @noazark, @sally, or @yellowapple help?

**Comment by chrisclark** [comment]
@daneah would love some help. Can you email me: cc@grove.co ?

**Comment by daneah** [comment]
@chrisclark will do! Look for something this weekend 😄

**Comment by surachai45** [comment]
I am waiting.

**Comment by daneah** [comment]
@surachai45: @chrisclark and I have talked offline about this and I may have the bandwidth to tackle it this weekend.

**Comment by daneah** [comment]
@sixsixtrample the main issue I'm trying to fix is the deprecation of `django.contrib.auth.views.login`. I haven't used the new `LoginView` yet and in Django 2.0+ I'm struggling to get it to redirect properly. I'm actively looking at it, but more eyes might be useful.

**Comment by daneah** [comment]
I think I've got it in place now, I'll be opening a PR quite soon 🤞

**Comment by daneah** [comment]
See #335

**Comment by daneah** [comment]
Release sounds imminent, just got my eyes on that PyPI version number 😄

**Comment by chrisclark** [comment]
Released!! Thanks for the help @daneah! Let me know if anyone spots problems.

**Comment by daneah** [comment]
Thanks @chrisclark!
