### ISSUE TITLE
404 page in the Show schema panel when using multipe db connection

### ISSUE THREAD

**Issue by rmaciejczyk** [groveco/django-sql-explorer#319]
I set up my project to use multiple database connections by using the EXPLORER_CONNECTIONS property. The New Query and Playground views work well however on both of them I get 404 page in the schema right panel.
This is because the schema call is made to /schema but according to the urls.py it should go to 'schema/(?P<connection>.+)$' so the path should include a connection name

**Comment by HenryMehta** [comment]
Same issue.

I resolved by replace `raise Http404` on line 163 of `views.py` with connection = `app_settings.EXPLOER_DEFAULT_CONNECTION`.  In short, if no schema connection is passed, use the default.  This is fine for me because I'm only connecting to 1 database.

**Comment by chrisclark** [comment]
Fixed by making the front-end always submit a connection in the form. This is cleaner than modifying the view, as going to /schema/somethingrandom should semantically return a 404. Plus this probably fixes some related, and as-yet-unreported, issues! Great find.
