### ISSUE TITLE
Import of schema in build_schema_cache_async is not relative

### ISSUE THREAD

**Issue by cguethle** [groveco/django-sql-explorer#322]
When attempting to run `build_schema_cache_async` as a part of building the schema view, a ModuleNotFound exception is thrown on the import (first line) of `build_schema_info` and `connection_schema_cache_key` from the schema module.

Changing the following (relative import) fixes it for me.
`from schema import build_schema_info, connection_schema_cache_key`
...to...
`from .schema import build_schema_info, connection_schema_cache_key`

Not sure if this is a setup problem on my part or a real issue. Seems like I shouldn't be the first one seeing this. :/ . Otherwise, my setup is very basic, inline with the README instructions.

**Comment by maxiplux** [comment]
hello thanks for this amazing project , but do you have any news about django 2.0 ?

**Comment by rpkilby** [comment]
@maxiplux see #318
