### ISSUE TITLE
customization requirement

### ISSUE THREAD

**Issue by mahmudkabir** [groveco/django-sql-explorer#326]
I need to run my app from office intranet. No internet is available there. NOw I need to store all the cdn files locally. How can I do that?

**Comment by randlet** [comment]
I have the same requirement as you.  You need to override the sql explorer base.html template in your app. So, in your app templates directory add a directory called explorer and then copy the explorer/base.html template to e.g. your_app/templates/explorer/base.html  Then modify the css/js links in your explorer/base.html file to replace the cdnjs links to local copies of the library.

**Comment by chrisclark** [comment]
Totally understood. If you want to look to open a PR for this, I'd be interested, but not something I'm likely going to spend on developing myself.

**Comment by marksweb** [comment]
@mahmudkabir @randlet 

I know it's now quite some time later, but someone recently provided a PR to serve all static assets from the application, so in the next release this will be possible.

**Comment by ernstki** [comment]
@marksweb would that have been #411 that implemented that?

**Comment by marksweb** [comment]
@ernstki Yes, that's the one by the looks of it.
