### ISSUE TITLE
Django==2.0.3 ModuleNotFoundError: No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by juliocebrito** [groveco/django-sql-explorer#330]
Hello friends, could you help me?

$ python manage.py migrate

  File "/Users/juliocebrito/Envs/niproyecciones/lib/python3.6/site-packages/explorer/models.py", line 10, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'

**Comment by rpkilby** [comment]
#318

**Comment by Dragonwarrior47** [comment]
I am also facing this issue

**Comment by marksweb** [comment]
Closing due to release on linked issue.
