### ISSUE TITLE
non admin user

### ISSUE THREAD

**Issue by rizplate** [groveco/django-sql-explorer#342]
how can a non-admin user see the explorer view? currently it directs to admin login

**Comment by randlet** [comment]
Haven't actually tried this but if you look in the settings docs: https://github.com/groveco/django-sql-explorer#settings you need to change the `EXPLORER_PERMISSION_VIEW` setting.

**Comment by atarla** [comment]
EXPLORER_PERMISSION_VIEW = lambda u: u.groups.filter(name='YOUR_GROUP_NAME').exists()
This worked for me.

**Comment by marksweb** [comment]
Include the URLs in a path not hanging off `/admin` and be very careful with access to this tool.
