### ISSUE TITLE
patch release breaks with "EXPLORER_DEFAULT_CONNECTION is None"

### ISSUE THREAD

**Issue by lsh-0** [groveco/django-sql-explorer#344]
I'm getting this after upgrading from `1.1.1` to `1.1.2`:
```
django.core.exceptions.ImproperlyConfigured: EXPLORER_DEFAULT_CONNECTION is None, but that alias is not present in the values of EXPLORER_CONNECTIONS
```

probably a result of this change: https://github.com/groveco/django-sql-explorer/blob/master/HISTORY#L12

I'm sure fixing my configuration will be trivial but I wanted to point out that if you're using a major.minor.patch semver approach to releases then a patch release should be backwards compatible and probably not break stuff.

**Comment by iurisilvio** [comment]
Had this issue today, really unexpected behaviour to a minor version change.

**Comment by krapuleng** [comment]
Thanks this works for me
