### ISSUE TITLE
need fix quotes on template

### ISSUE THREAD

**Issue by mmmcorpsvit** [groveco/django-sql-explorer#348]
base.html

```html
<a class="navbar-brand" href="{% url "explorer_index" %}">SQL Explorer</a>
```
contain same quotes, but must contain not same

**Comment by AdamDonna** [comment]
Mixing quote types should fix this. Is this still an issue?

**Comment by BusinessFawn** [comment]
Created a PR for this one.

**Comment by marksweb** [comment]
Excellent, thank you @BusinessFawn I hadn't seen this issue yet. Not sure I'd quite gone this far back.

I think we can get this into 2.1 which isn't far away.
