### ISSUE TITLE
Not run at open Query

### ISSUE THREAD

**Issue by samazaphikel** [groveco/django-sql-explorer#361]
Hi,
how is it possible not to execute the query immediately? Sometimes I want to read first if this is the right query and not to load the database unnecessarily.

**Comment by arpitremarkable** [comment]
You can click the "Play" link to open up sql in playground mode, it wouldn't have executed by default.

**Comment by chrisclark** [comment]
Also, if you want to get tricky, there is a somewhat-undocumented feature -- you can put ?show=0 in the URL and the query will not execute. You can then use the "Save Only" option from the Run drop down.
