### ISSUE TITLE
Blacklisting of 'DROP' conflicting with table/column name

### ISSUE THREAD

**Issue by aniruddha-adhikary** [groveco/django-sql-explorer#371]
A select query requires me to look up columns and tables with the word 'drop' in their name. SQL Explorer denies to run that query. Although it is perfectly safe.

![Screenshot 2019-09-11 at 3 30 36 PM](https://user-images.githubusercontent.com/932949/64685729-47c27a80-d4a9-11e9-9d1c-afa630b07dd1.png)

**Comment by chrisclark** [comment]
yep - kinda annoying. But you can override EXPLORER_SQL_BLACKLIST parameter in settings if you want to allow that word. If you are using a readonly connection (WHICH YOU SHOULD BE!! ;) then you can even set the blacklist to an empty set.

**Comment by marksweb** [comment]
@aniruddha-adhikary Just come across this issue & good news.

In #414 I've improved the blacklist check so that when a blacklisted word is part of a word, it won't get flagged.

This is unreleased but I think 2.1 is probably not far away from releasing.
