### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by devova** [groveco/django-sql-explorer#376]
Please add support of Django 3

**Comment by pvidtec** [comment]
Same issue
==========

```

container_django_intranet_dev |   File "/opt/intranet/docker/.venv/lib/python3.8/site-packages/explorer/urls.py", line 2, in <module>
container_django_intranet_dev |     from explorer.views import (
container_django_intranet_dev |   File "/opt/intranet/docker/.venv/lib/python3.8/site-packages/explorer/views.py", line 15, in <module>
container_django_intranet_dev |     from django.shortcuts import get_object_or_404, render, render_to_response
container_django_intranet_dev | ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (/opt/intranet/docker/.venv/lib/python3.8/site-packages/django/shortcuts.py)
```

**Comment by Anton-Shutik** [comment]
@devova @pvidtec  Would you mind adding PR for that?

**Comment by muflone** [comment]
any news on merging the PR #377 ?

**Comment by airstrike** [comment]
@muflone  In the meantime, one can always install the forked / patched repo

    pip install git+https://github.com/rob-deutsch/django-sql-explorer.git@django3

**Comment by devova** [comment]
It looks like the author doesn't want to maintain the package.
@rob-deutsch would you ming to publish a new package to pypi and call it for example `django3-sql-explorer`?

**Comment by francischew** [comment]
Any ETA on this merge?  Thanks.

**Comment by Anton-Shutik** [comment]
@francischew #377 doesn't have django3 in travis conf. This way we can't make sure the app is compartible with django 3

**Comment by mjhanke** [comment]
Could a new version be released since this MR has been merged? https://github.com/groveco/django-sql-explorer/pull/387

**Comment by Anton-Shutik** [comment]
@chrisclark looks like you have that permission :)
