### ISSUE TITLE
Hitting the Format Button results in a 403 or 405 error

### ISSUE THREAD

**Issue by zurtri** [groveco/django-sql-explorer#389]
When hitting the format button I get

In Browser:
POST http://localhost:8000/explorer/format/ 403 (Forbidden)

In CLI:
Forbidden (CSRF token missing or incorrect.): /explorer/format/
WARNING 2020-05-08 11:38:33,843 log 9560 1008 Forbidden (CSRF token missing or incorrect.): /explorer/format/
 "POST /explorer/format/ HTTP/1.1" 405 2513

I've refreshed and the checked that the CSRF token is being rendered (it is), but still get the same issue. Saving a query is fine.

Any ideas?

**Comment by alxnik** [comment]
Same issue here albeit in the /explorer/[id]/email_csv endpoint.

It is related to the CSRF_COOKIE_HTTPONLY django setting. If it is enabled, the buttons do not work. Keep in mind that even if you disable the setting, you have to reset the cookie on the browser too (either restart the browser or go to developer tools->storage->find the csrftoken cookie->HttpOnly=False - this is no firefox)

**Comment by marksweb** [comment]
Project setting/config related, not an issue, closing.
