### ISSUE TITLE
Query containing non-ASCII characters prevents preview rendering

### ISSUE THREAD

**Issue by marksweb** [groveco/django-sql-explorer#400]
If your query contains weird characters (I'm guessing non-ASCII) in the column headings, the entire preview table doesn't get rendered.  E.g. Try doing `SELECT 'thing' AS "This costs £100`

**Comment by marksweb** [comment]
This may be resolved in the latest version. Need to confirm with the person who raised this with me.

**Comment by spapas** [comment]
Hello @marksweb I tested it on the latest version using the following query having unicode (greek) characters and it works fine:

```
select aa.small_name as "Όνομα", count(*) as "Αριθμός" from yearly_yearlysupply yy 
LEFT JOIN 
authorities_authority aa on yy.authority_id = aa.id
group by aa.small_name
```

**Comment by marksweb** [comment]
I also tested this on the last released version, so my source for this bug may actually have an old version installed. Closing.
