### ISSUE TITLE
Schema sidebar takes cursor focus

### ISSUE THREAD

**Issue by marksweb** [groveco/django-sql-explorer#401]
The schema sidebar, when opened automatically on page load, takes the cursor focus.

This can be annoying

**Comment by chrisclark** [comment]
Yeah this is super annoying 👍

**Comment by marksweb** [comment]
I think this may be resolved in v2

I've had a look at a system with an older version installed and you can add `?schema=1` to your URL to show the schema. That doesn't seem to work in v2, but if you have the schema open and refresh, my cursor stays in the SQL editor & the schema stays open (so I assume the cookie is doing it's job).
