### ISSUE TITLE
DML

### ISSUE THREAD

**Issue by jayvdb** [groveco/django-sql-explorer#405]
I tried removing `UPDATE` from the blacklist, and that allows DML to be submitted without error, but after successfully handling the DML, the UI gives no clue what happens after that, and it appears it didnt do the update.

**Comment by marksweb** [comment]
I can't replicate this.

Removing `UPDATE` from my blacklist, running an update does change data.

I use django-allauth, so running the following changes data;

```
UPDATE account_emailaddress e
SET verified = false
WHERE e.id = 3;
```

**Comment by jayvdb** [comment]
ok, confirmed it is working. Not sure what I did wrong last time.
Thanks for your patience.
