### ISSUE TITLE
Refactor README into docs

### ISSUE THREAD

**Issue by marksweb** [groveco/django-sql-explorer#407]
There's a branch which is quite old & didn't get too far with the task of creating sphinx docs;

https://github.com/groveco/django-sql-explorer/tree/docs

_(I've merged master to sync it)_

It would be ideal to refactor the README into proper docs, leaving a simple 'getting start' type overview for a README. There's far too much detail in there at the moment.

**Comment by bojanderson** [comment]
If you're still looking for help with this. I could help.

**Comment by marksweb** [comment]
@bojanderson that would be ideal. 👍

**Comment by bojanderson** [comment]
@marksweb should I add a folder called docs and then put all the documents in there? And then put links from the readme to the various documents in the folder? I'll pry break it up by major headings.

Once I got that feedback I'll make a fork and try to get it done in a couple days during my free time.

**Comment by marksweb** [comment]
Resolved by #410 and #416
