### ISSUE TITLE
I have a problem `created_by_user_email` method

### ISSUE THREAD

**Issue by soulwawa** [groveco/django-sql-explorer#422]
HI, thank you for the django-sql-explorer

i have a problem below code

https://github.com/groveco/django-sql-explorer/blob/962874523390a575105dde3a0dfdcecf881384db/explorer/forms.py#L54-L57

i made it Customizing authentication in Django(https://docs.djangoproject.com/en/2.2/topics/auth/customizing/)

i don`t have ```'User' object has no attribute 'email'```

Please help me with what to do. thank you.

**Comment by marksweb** [comment]
@soulwawa You have a custom `User` model which doesn't have an `email` for users?

**Comment by soulwawa** [comment]
@marksweb i changed ```email ``` to ```user_email ```

**Comment by marksweb** [comment]
@soulwawa So in some python, for your `User` model, you might do something like...

```python
from django.contrib.auth import get_user_model

User = get_user_model()

first_user = User.objects.first()

email = first_user.user_email
```

If so, I would recommend you add a property to the user model for compatibility with things which expect a `User` instance to have an email. I'd say it's uncommon not to be able to do `user.email`.

```python
    @property
    def email(self):
        """
        Compatibility property to provide email value
        """
        return self.user_email
```

**Comment by soulwawa** [comment]
@marksweb Thank you so much for your explanation.

I have one more question. can i  change ```email``` attribute to another attribute ?
For example, django Settings ?

**Comment by marksweb** [comment]
Not currently.

The application expects an email address so it uses `email` because, unless you customise your `User` like you have, it will be available.

**Comment by soulwawa** [comment]
Thank you very much indeed! @marksweb
