### ISSUE TITLE
On creating a new Query , panel-content not visible (2.1.0),

### ISSUE THREAD

**Issue by m-libbrecht** [groveco/django-sql-explorer#431]
On clicking the 'New Query' navbar, the panel-content is still collapsed (display:none),  the sql_toggle glyphicon (resize-full glyphicon) is not visible.  Not able to create a new sql query

**Comment by marksweb** [comment]
@m-libbrecht thanks for raising - not sure how I missed that.

Will have a fix out shortly.

**Comment by marksweb** [comment]
@m-libbrecht Install 2.1.2 for the fix 👍
