### ISSUE TITLE
Enhancement Request - Full Screen Results should show filtered results, not all results

### ISSUE THREAD

**Issue by MYX-GitHub** [groveco/django-sql-explorer#433]
The Full Screen Results is a great feature, but somewhat limited because it always shows all query results, whereas the many screen can show results that are filtered through the use of parameters (i.e. - the main screen with filtering parameters can show 100 records, but opening the Full Screen Results shows 1000 results, because it is unfiltered)

Is it possible to enable the Full Screen Results to show only the query results that match the additional parameters (i.e. both screens only show the 100 filtered results)?

Thanks!

Mike

**Comment by marksweb** [comment]
Can you give an example please? Perhaps with screenshots & the type of URL params you're talking about.

**Comment by MYX-GitHub** [comment]
Thanks for looking into this.

Here's an example  query with a filtering parameter "$$Domain$$":

SELECT
	Domain,
	EntityType AS 'Entity Type',
	COALESCE(EntitySubtype, '') AS 'Entity Sub-Type',
	COUNT(*) AS 'Qty'

FROM
	ACTGEAR

WHERE
	Domain LIKE '$$Domain$$%'
	AND EntityType LIKE '%'
	AND RuleStatus NOT IN ('Dev', 'Draft')

GROUP BY
	Domain, EntityType, EntitySubtype
	
ORDER BY
	Domain, EntityType

The URL on the main screen for the unfiltered query returns 937 rows:

http://127.0.0.1:8000/explorer/13/?params=domain%3A

The URL on the "Full Screen Results" link is:

http://127.0.0.1:8000/explorer/13/?fullscreen=1&rows=1000

Specifying a Domain Parameter of "Business" filters the results and only shows 26 rows.

 The URL on the main screen for the filtered query that returns the 26 rows:

http://127.0.0.1:8000/explorer/13/?params=domain%3ABusiness

The URL on the Full screen Results link is (the same as when the main screen was unfiltered:

http://127.0.0.1:8000/explorer/13/?fullscreen=1&rows=1000

(I took 2 screen captures, but for some reason, I can't attach the PDF files. Will try something different and attach later.)

**Comment by MYX-GitHub** [comment]
Can't attach files for some reason - GitHub allows me to select a file to open, but doesn't attach it.

I tried SQL Explorer and attaching files in two different browsers and got the same results (FireFox and Pale Moon - a FireFox clone)

Let me know if you'd like the screen captures emailed.

Regards,

Mike

**Comment by MYX-GitHub** [comment]
I'm not really setup to submit a PR (Rather than a developer, I'm a hacker who can code myself out of a paper bag, as long as it is sufficiently wet.) I'll try updating my installed code with your lines 33 and 35 above and let you know how it works.

**Comment by MYX-GitHub** [comment]
Ok, my mistake ... lines 33 and 35 are where the fix would go (they aren't actually the fixed lines). I'll scratch my head a little bit to see if I can come up with something, but with my level of coding skills, I'm not even sure where on my head I should be scratching.

**Comment by marksweb** [comment]
@MYX-GitHub ah ok, sorry, I just assume that people using this are likely to be python devs.

I've pushed a branch which hopefully resolves this. You can install from it directly and test it using;

`pip install git+https://github.com/groveco/django-sql-explorer.git@fix/433`

**Comment by marksweb** [comment]
This should be resolved in #442 442
