### ISSUE TITLE
EXPLORER_PERMISSION_VIEW does not seem to get current user in latest 2.1.2 release

### ISSUE THREAD

**Issue by francischew** [groveco/django-sql-explorer#435]
I have the following configuration in settings.py

EXPLORER_PERMISSION_VIEW = lambda u: u.is_staff
EXPLORER_PERMISSION_CHANGE = lambda u: u.is_superuser or u.groups.filter(name='full_query_explorer').exists()

Running against django-sql-explorer==2.1.2 version configuration gives the following error against http://localhost:8000/explorer:

AttributeError at /explorer/
'WSGIRequest' object has no attribute 'is_staff'

Reverted back to django-sql-explorer==2.0 version configuration and explorer permissions are behaving as expected.

**Comment by marksweb** [comment]
That's right, as of 2.1 the request object is passed to those, not the user object.

Update your lambda to do something like `lambda r: r. user.is_staff`

**Comment by francischew** [comment]
Thanks Mark.  Much appreciated for the quick response.
