### ISSUE TITLE
Overriding Login View

### ISSUE THREAD

**Issue by dannyshaw** [groveco/django-sql-explorer#440]
We have a custom login that enforces Google Auth. However attempting to access explorer allows a login without auth via the SafeLoginView. 

There doesn't appear to be a way to specify a custom login view/redirect? 
If not would you accept a PR implementing an override?

**Comment by marksweb** [comment]
Hi @dannyshaw, I'd be happy for a PR for this 👍

**Comment by sunjiali** [comment]
Hi dannyshaw@,

Are you working on this PR?

**Comment by dannyshaw** [comment]
Hi @sunjiali, we're working on this issue in our current sprint (well, @ddouglascarr is)

We're not totally sure what direction you'd want to take this as repo owner. For our purposes just allowing a view to be provided in settings that will be returned when `handle_no_permission()` is called on will suffice.

@ddouglasscarr will raise a PR once the approach we're taking is implemented on our fork.

**Comment by sunjiali** [comment]
Hi @dannyshaw,

I have custom login and I am not use django admin. Maybe same with you. 

So could you share the code of  `allowing a view to be provided in settings that will be returned when handle_no_permission() is called on will suffice.`  I am not familiar with django-sql-explorer. 

Thanks

**Comment by marksweb** [comment]
Hi @dannyshaw @ddouglascarr

If you had this has a setting which would load your preferred view or default to `SafeLoginView` then I think that'd be most suitable.

**Comment by marksweb** [comment]
This has been included in 2.2 which I've just released.
