### ISSUE TITLE
Deprecation warnings for `ugettext_lazy`

### ISSUE THREAD

**Issue by brettdh** [groveco/django-sql-explorer#446]
Lots of messages like these:

```
explorer/models.py:61: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```

This appears to be [a compat shim for Python 2](https://code.djangoproject.com/ticket/30165) - but since this library has [dropped Python 2 support](https://github.com/groveco/django-sql-explorer/blob/master/HISTORY.rst#200-2020-10-09), it should be safe to change uses of `ugettext_lazy` to `gettext_lazy`.

**Comment by marksweb** [comment]
@brettdh yeah I didn't get chance to look into when `gettext_lazy` was introduced. I'd imagine they included it in 2.2 so I'd be happy to swap to it already.
