### ISSUE TITLE
How I can use this for each user?

### ISSUE THREAD

**Issue by AhmedSalam22** [groveco/django-sql-explorer#452]
How i can show only the queryset for each user?
each user just can query their data not all user can query other user data
Hope you understand me

**Comment by marksweb** [comment]
@AhmedSalam22 This application allows SQL queries to be ran against a database. You might consider that the opposite of restricting access to data.

If you want to restrict access to data, this probably isn't the application you really want.

**Comment by AhmedSalam22** [comment]
@marksweb  Thank you so much
