### ISSUE TITLE
Query form submission closes connection

### ISSUE THREAD

**Issue by sdether** [groveco/django-sql-explorer#457]
If I have a query (either saved or in the playground) that runs longer than 30 seconds, the app closes the connection. It doesn't seem to be a django or db timeout, as I have a DRF view to execute SQL and using that view with the same SQL and DB connection, I can run queries that take several minutes.

Is there a SQL Explorer specific setting for timeouts?

**Comment by lawson89** [comment]
@marksweb @sdether this is configured at the db connection level (not something that SQL explorer controls).
It's different per DB. Here is a relevant article for postgres. I feel we should close this issue.

https://medium.com/squad-engineering/configure-postgres-statement-timeouts-from-within-django-6ce4cd33678a
