### ISSUE TITLE
Features request: Add pivot table save option and export to excel options

### ISSUE THREAD

**Issue by lokeshmyadav** [groveco/django-sql-explorer#459]
Features request: Add pivot table save option and export to excel options

**Comment by marksweb** [comment]
@lokeshmyadav Do you have `xlsxwriter` installed?

If you do, you should have the save as excel option available;

<img width="207" alt="Screenshot 2021-10-02 at 21 18 45" src="https://user-images.githubusercontent.com/1461191/135730792-ac4b9664-f2d9-433b-818d-25be0d1980f7.png">

**Comment by lokeshmyadav** [comment]
I wanted download option for pivot table .. if I save with option above, it
will download queries results, not the pivot table

**Comment by lawson89** [comment]
@marksweb is this one ok to close now?
