### ISSUE TITLE
Whitespace wraps SQL when a query is saved

### ISSUE THREAD

**Issue by marksweb** [groveco/django-sql-explorer#468]
When you save a query whitespace is added to the beginning and end.

**Comment by fearless0307** [comment]
@marksweb I got the issue. Can i push a fix?

**Comment by marksweb** [comment]
@fearless0307 yes, please do!

**Comment by fearless0307** [comment]
@marksweb Please check. https://github.com/groveco/django-sql-explorer/pull/471

**Comment by marksweb** [comment]
Released in 2.4.1

https://pypi.org/project/django-sql-explorer/
