### ISSUE TITLE
Vulnerabilities in JS files

### ISSUE THREAD

**Issue by fearless0307** [groveco/django-sql-explorer#469]
Hi Team,

Can we please upgrade the JS files?

These packages have some Vulnerabilities:
https://snyk.io/vuln/npm:bootstrap@3.3.7
https://snyk.io/vuln/npm:jquery@3.3.1
https://snyk.io/vuln/npm:jquery-ui@1.12.1
https://snyk.io/vuln/npm:underscore@1.8.3

Thanks,
Bhola

**Comment by marksweb** [comment]
Absolutely. @fearless0307 can you raise a PR?

**Comment by fearless0307** [comment]
What's the test strategy here, as bootstrap up-gradation might break UI.

**Comment by marksweb** [comment]
@fearless0307 I've never changed the frontend very much, just adding a button to expand/collapse the sql field really.

So I'd say there isn't a strategy beyond changing something & checking it works. There's no js unit testing or frontend tests to run.

**Comment by fearless0307** [comment]
Ok, I will change and see if everything works fine or not.

**Comment by marksweb** [comment]
Fantastic! Thank you @fearless0307

**Comment by fearless0307** [comment]
@marksweb Bootstrap 4/5 comes with major changes.
For now, we can upgrade from 3.3.6 to 3.4.1
This version doesn't have any know vulnerabilities.
https://snyk.io/vuln/npm:bootstrap@3.4.1
Also upgrading Jquery from 2.1.4 to 3.6.0 is working fine.

While doing research, I found out that jQuery Cookie is archived. A new package with similar functionality is available js-cookie. https://github.com/js-cookie/js-cookie

**Comment by marksweb** [comment]
Thanks @fearless0307

That sounds sensible.

I might take a look at moving to bootstrap 5 once you're done. There aren't that many templates so it's likely easier than upgrading the Celery and S3 integration thay I was looking at recently 😂

**Comment by fearless0307** [comment]
@marksweb https://github.com/groveco/django-sql-explorer/pull/470
I used almost all UI-related features, to check if any UI broke. Everything seems fine. No console error.
Please review once.

Thanks.

**Comment by fearless0307** [comment]
Pull Request https://github.com/groveco/django-sql-explorer/pull/470 Merged.
