### ISSUE TITLE
Improve template to make easier to customize them for integration with the project

### ISSUE THREAD

**Issue by nad2000** [groveco/django-sql-explorer#477]
I added a link in the nav bar to get back to the main project application. For that, I had to modify 4 templates: query_list.html, query.html, play.html and qyertlog_list.html even though the base.html has the block for the navbar links, and doesn't get reused. So I had to customise 4 templates to get it working. 

Also, to add some extra styling, I had to rewrite the entire base.html, since there are no blocks for header parts, ie, CSS.

**Comment by lawson89** [comment]
@marksweb this has been merged so we are good to close?
