### ISSUE TITLE
Format button not working

### ISSUE THREAD

**Issue by avi-perl** [groveco/django-sql-explorer#492]
Clicking the format button is not working. 
When I click the text on the button, nothing happens at all. If I select another part of the button, I get the following:
> Forbidden (403)
> CSRF verification failed. Request aborted.

**Comment by lawson89** [comment]
Ok I just ran into this exact issue on a project of mine and finally figured it out. It was this setting which security had mandated

CSRF_COOKIE_HTTPONLY = True

Explanation from Django docs below

CSRF_COOKIE_HTTPONLY[¶](https://docs.djangoproject.com/en/4.1/ref/settings/#csrf-cookie-httponly)

Default: False

Whether to use HttpOnly flag on the CSRF cookie. If this is set to True, client-side JavaScript will not be able to access the CSRF cookie.

**Comment by marksweb** [comment]
@lawson89 Thank you for clarifying this.

I don't turn that setting on because of the problems it causes in javascript so I've not seen this.

Perhaps we need some additional docs to clarify this django setting in relation to this functionality.

**Comment by lawson89** [comment]
Ok sure I am happy to take a crack at adding this in the docs if you would like

**Comment by marksweb** [comment]
@lawson89 That would be great if you could please! 🥇
