### ISSUE TITLE
Email popup does not display form

### ISSUE THREAD

**Issue by lawson89** [groveco/django-sql-explorer#499]
When I click on the email icon - I see an empty popup

I had to add the following flag to the popover to allow the form to display 
    sanitize: false,

I'll submit an MR if someone else can confirm that the popover is broken for them

**Comment by marksweb** [comment]
I can't confirm this at the moment as I don't use the app with tasks enabled.

**Comment by lawson89** [comment]
Ok this was accidentally broken when bootstrap was updated to 3.4.1 since they started sanitizing the html content of the popovers. I'll have this small PR in a minute. I came across this while testing the celery5 stuff
