### ISSUE TITLE
Premature imports in version 2.5.0

### ISSUE THREAD

**Issue by vsemionov** [groveco/django-sql-explorer#507]
Matplotlib and Seaborn are imported unconditionally by sql explorer, even if charts are disabled in the settings. As a result, these libraries are imported every time our Django application starts up. This increases the memory consumption of our server and some long-running management commands. We only have Matplotlib installed (not Seaborn), and see about **50 MB more memory used**.

Additionally, the following is now scattered in our daily maintenance logs and email reports:
```
[38:MainThread] [none] [matplotlib.font_manager] INFO: generated new fontManager
```
The above is also a result of Matplotlib initialization on a pristine filesystem.

Can we please import the chart-related libraries **only if charts are enabled in settings**?

**Comment by marksweb** [comment]
That looks sensible to me. Thanks @lawson89

**Comment by vsemionov** [comment]
Looks good, thank you @lawson89
