### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by lawson89** [groveco/django-sql-explorer#516]
@marksweb I have some work that I'd like to do to make the project a better fit for smaller sites 
For instance, I have sites that don't use S3/celery but I'd still like to make use of the snapshot/email a report features

But before tackling that I wonder if a general issue cleanup is in order to clear the plate? 
I'd be happy to knock some of the remaining issues out but there are a lot that I'm not sure are still valid.

Let me know how I can help
Thanks!

**Comment by lawson89** [comment]
Also I know you have 3.9/3.10 support that should be pretty close now

**Comment by marksweb** [comment]
@lawson89 sounds great!

I've just done a little cleanup of issues & PRs. My ones related to new python versions were solved by your recent work.

The project has support now for all current python versions and django. I also added testing against the Django development branch.

Do you want to take a look at issues for something that you'd like to do & ask me if you've got any questions?

**Comment by lawson89** [comment]
Yep - I'll take a quick look and either work on or if no longer an issue I'll post a comment on the ticket
