### ISSUE TITLE
latest release (3.1) tries to execute migrations

### ISSUE THREAD

**Issue by scastlara** [groveco/django-sql-explorer#527]
When running `django-sql-explorer==3.1` in my django application, I see it tries to generate migrations if I run `python manage.py makemigrations`.

```
venv/bin/python src/manage.py makemigrations --check

Migrations for 'explorer':

venv/lib/python3.11/site-packages/explorer/migrations/0012_alter_queryfavorite_query_alter_queryfavorite_user.py
  - Alter field query on queryfavorite
  - Alter field user on queryfavorite

```

are some migrations missing or something? latest I see here is [0011](https://github.com/groveco/django-sql-explorer/blob/master/explorer/migrations/0011_query_favorites.py)

**Comment by scastlara** [comment]
see this https://github.com/groveco/django-sql-explorer/pull/528
just a fresh clone and `python manage.py makemigrations`. They are indeed missing. Don't know what setup you guys have for CI, but you could consider adding `python src/manage.py makemigrations --check` as a step to avoid that from happening. That is, if you want of course!

**Comment by marksweb** [comment]
Looks like the migrations check can actually be added as a pre-commit hook 👍
