### ISSUE TITLE
Error: Page does not load if `AUTH_USER_MODEL` does not have `id` field

### ISSUE THREAD

**Issue by eeriksp** [groveco/django-sql-explorer#543]
In my Django project I have overridden `AUTH_USER_MODEL` so that it its `id` field is renamed to `person_id`.
This causes the line 90 in `explorer/views/list.py` to break:

```py
query_favorites_for_user = QueryFavorite.objects.filter(user_id=self.request.user.id).values_list
```
The line should be updated so that `user.pk` would be used instead of `user.id`.

```py
query_favorites_for_user = QueryFavorite.objects.filter(user_id=self.request.user.pk).values_list
```

Since `pk` refers to the models's primary key regardless of what the actual field name is, it is guaranteed to always be present.

**Comment by marksweb** [comment]
Yeah, valid point 👍 

Happy to accept a PR on this.

**Comment by eeriksp** [comment]
PR is here: https://github.com/groveco/django-sql-explorer/pull/544
