### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by cormier** [groveco/django-sql-explorer#96]
Hi,
First of all, I would like to thank all the contributors for their efforts on making this project **great**! :smile: 

It does everything that I need to do, except for one thing: I cannot localize it because it is not internationalized. I was wondering if there was any plans to internationalize the project? I'm afraid I do not have much time to do it myself at the moment. If anyone has time to do it, I can promise, however, that I will contribute the french canadian localization.

**Comment by marksweb** [comment]
@cormier I know it's been 5 years, but #345 added (some) Chinese translation.

If you're still using the app, we could add French Canadian. The main problem with localisation is having the people with the knowledge/ability to do it.

**Comment by cormier** [comment]
Thanks @marksweb for following-up! I should have been more careful when making promises, because things have changed for me in the past 5 years and I'm afraid that I will not be able to deliver this French Canadian localization after all :sweat_smile:

Maybe the project I was working on back then still has a use case for this. I'll try to get in touch with them and and let them know it's now supported.

**Comment by marksweb** [comment]
Well, 5 years is a long time, so I'm not surprised!

Thanks @cormier! 😄
